version: "3"
services:
  my-telldus-core-mqtt:
    build:
      context: ../
    container_name: dev_my_telldus-core-mqtt
    restart: unless-stopped
    depends_on:
      - mosquitto
    environment:
      - TDM_MQTT_SERVER=mosquitto
      - TDM_MQTT_USER=telldus-core-mqtt
      - TDM_MQTT_PASS=telldus-core-mqtt
    devices:
      - /dev/null:/dev/bus/usb:rwm
    volumes:
      - ./tellstick.conf:/etc/tellstick.conf:ro

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf

  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    restart: unless-stopped
    ports:
      - "5353:5353"
    volumes:
      - ./hass:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Stockholm

volumes:
  mosquitto_data:
